USE DULICHVIETNAM

INSERT INTO QUYEN VALUES(N'Admin')
INSERT INTO QUYEN VALUES(N'Người Dùng')

INSERT INTO ADMIN VALUES('admin1','123',N'Nguyễn Thanh Hoa',1)
INSERT INTO ADMIN VALUES('admin2','456',N'Nguyễn Trọng Đức',1)


