--CREATE DATABASE DULICHVIETNAM
GO

USE DULICHVIETNAM

CREATE TABLE QUYEN(
	MaQuyen INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	TenQuyen NVARCHAR(50) NULL
)

CREATE TABLE ADMIN(
	TenDNAdmin NVARCHAR(50) NOT NULL PRIMARY KEY,
	MK VARCHAR(50) NULL,
	HoTen NVARCHAR(50) NULL,
	MaQuyen INT NULL,
	FOREIGN KEY(MaQuyen) REFERENCES dbo.Quyen(MaQuyen)
)

CREATE TABLE KHACHHANG(
	MaKH VARCHAR(50) NOT NULL PRIMARY KEY,
	TenKH NVARCHAR(50) NULL,
	NgaySinh date NULL,
	GioiTinh INT NULL,
	SDT VARCHAR(10) NULL,
	Email VARCHAR(50) NULL,
	TenDN VARCHAR(50) UNIQUE,
	MK VARCHAR(50) NULL,
	MaQuyen INT NULL,
	FOREIGN KEY(MaQuyen) REFERENCES dbo.QUYEN(MaQuyen)
)
GO

CREATE TABLE KHACHSAN(
	MaKS VARCHAR(50) NOT NULL PRIMARY KEY,
	TenKS NVARCHAR(50) NULL,
	DiaChi NVARCHAR(50) NULL,
	SoPhong INT NULL
)
GO

CREATE TABLE LOAIPHONG(
	MaLP VARCHAR(50) NOT NULL PRIMARY KEY,
	TenLoai NVARCHAR(50) NULL,
	GiaPhongDon FLOAT NULL,
	GiaPhongDoi FLOAT NULL,
	MaKS VARCHAR(50) NULL,
	FOREIGN KEY(MaKS) REFERENCES dbo.KHACHSAN(MaKS)
)
GO

CREATE TABLE PHUONGTIEN(
	MaPT VARCHAR(50) NOT NULL PRIMARY KEY,
	TenPT NVARCHAR(50) NULL,
	SoCho INT NULL,
	BienKS VARCHAR(50) NULL
)
GO

CREATE TABLE TINHTHANH(
	MaTT VARCHAR(50) NOT NULL PRIMARY KEY,
	TenTT NVARCHAR(50) NULL
)
GO

CREATE TABLE TOUR(
	MaTour VARCHAR(50) NOT NULL PRIMARY KEY,
	TenTour NVARCHAR(100) NULL,
	GiaTour FLOAT NULL,
	SoLuong INT NULL,
	NgayKhoiHanh date NULL,
	ThoiGian FLOAT NULL,
	DichVu NVARCHAR(100) NULL,
	HinhAnh NVARCHAR(200) NULL,
	HanhTrinh NVARCHAR(200) NULL,
	NoiXuatPhat NVARCHAR(50) NULL,
	MaTT VARCHAR(50) NULL,
	MaPT VARCHAR(50) NULL,
	FOREIGN KEY(MaTT) REFERENCES dbo.TINHTHANH(MaTT),
	FOREIGN KEY(MaPT) REFERENCES dbo.PHUONGTIEN(MaPT)
)
GO

CREATE TABLE HUONGDANVIEN(
	MaHDV VARCHAR(50) NOT NULL PRIMARY KEY,
	TenHDV NVARCHAR(50) NULL,
	SDT VARCHAR(10) NULL,
	DiaChi NVARCHAR(50) NULL
)
GO
CREATE TABLE DATTOUR(
	MaTour VARCHAR(50) NOT NULL,
	MaKH VARCHAR(50) NOT NULL,
	SoLuongNL INT NULL,
	SoLuongTE INT NULL,
	NgayDat date NULL,
	MaLP VARCHAR(50) NULL,
	YeuCau NVARCHAR(100) NULL,
	MaHDV VARCHAR(50) NULL,
	PRIMARY KEY(MaTour,MaKH),
	FOREIGN KEY(MaTour) REFERENCES dbo.TOUR(MaTour),
	FOREIGN KEY(MaKH) REFERENCES dbo.KHACHHANG(MaKH),
	FOREIGN KEY(MaLP) REFERENCES dbo.LOAIPHONG(MaLP),
	FOREIGN KEY(MaHDV) REFERENCES dbo.HUONGDANVIEN(MaHDV)
)



